sudo: false
language: python
cache:
  directories:
  - "$HOME/.cache/pip"
matrix:
  include:
  - python: 2.7
    env: TOXENV=flake8
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: pypy
    env: TOXENV=pypy
install:
- pip install tox codecov
script:
- tox -e $TOXENV
after_success:
- codecov
notifications:
  irc:
    channels:
      - "chat.freenode.net#falconframework"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
